# Generated by Django 3.2 on 2021-04-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='Product id')),
                ('name', models.TextField(verbose_name='Project Name')),
                ('age_resticted', models.BooleanField(verbose_name='Is age restricted')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
        ),
    ]
