# Generated by Django 3.2 on 2021-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_auto_20210419_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shoppingcarthistory',
            name='action',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
