# Generated by Django 3.2 on 2021-04-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_shoppingcarthistory_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.AlterField(
            model_name='shoppingcarthistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.product', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='shoppingcarthistory',
            name='shoppingCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.shoppingcart', verbose_name='Cart'),
        ),
    ]
