# Generated by Django 3.2 on 2021-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_auto_20210419_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=123456789012, max_length=12, verbose_name='Bar Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='imageName',
            field=models.CharField(default='image.png', max_length=50, verbose_name='Image Name'),
            preserve_default=False,
        ),
    ]
